
import React, { useState } from 'react';
import { Download, Calculator, Sparkles } from 'lucide-react';
import { TRANSLATIONS } from '../constants';
import { Language } from '../types';

interface ResourcesProps { lang: Language; }

const Resources: React.FC<ResourcesProps> = ({ lang }) => {
  const t = TRANSLATIONS[lang];
  const [sales, setSales] = useState(100000);
  const [traffic, setTraffic] = useState(50);
  const [conv, setConv] = useState(20);
  const [shopType, setShopType] = useState('Grocery / Kirana');
  const isIndic = lang === 'gu' || lang === 'hi';

  const potential = (traffic * (conv / 100) * (sales / (traffic * (conv / 100) || 1)) * 1.3).toFixed(0);

  // Functional Download Helper with Highly Professional Formatting
  const generateProfessionalContent = (title: string, data: string) => {
    const separator = "=".repeat(60);
    const subSeparator = "-".repeat(60);
    return `
${separator}
[ SHOPSAHAY GUJARAT - RETAIL GROWTH PARTNER ]
${separator}

OFFICIAL DOCUMENT: ${title.toUpperCase()}
DATE OF EXPORT: ${new Date().toLocaleString()}
REGIONAL OFFICE: Remote HQ - Gujarat, India
CONTACT: support@shopsahay.com | growth.shopsahay.com

${separator}

${data}

${separator}
Generated by ShopSahay Professional Resources 2024
This document is a proprietary tool of ShopSahay.
For full audit sessions, visit our portal.
${separator}
`;
  };

  const handleDownload = (filename: string, content: string, type: string = 'text/plain') => {
    const formattedContent = generateProfessionalContent(filename.split('_').join(' ').replace('.txt', ''), content);
    const blob = new Blob([formattedContent], { type });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = filename;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const freebies = [
    { 
      type: 'Excel', 
      title: 'Daily Cash Flow Tracker', 
      color: 'bg-green-100 text-green-700',
      filename: 'Daily_Cash_Flow_Tracker_ShopSahay.txt',
      content: `
FINANCIAL TRACKING SHEET
-------------------------
DATE       | INFLOW DESCRIPTION    | AMOUNT (₹) | OUTFLOW DESCRIPTION   | AMOUNT (₹) | STATUS
-----------|-----------------------|------------|-----------------------|------------|--------
01/Oct/24  | OPENING BALANCE       | 10,000.00  | N/A                   | 0.00       | START
01/Oct/24  | RETAIL CASH SALES     | 5,450.00   | STAFF SALARY ADVANCE  | 1,000.00   | PENDING
01/Oct/24  | UPI PAYMENTS          | 2,200.00   | UTILITY BILL          | 450.00     | PAID
-----------|-----------------------|------------|-----------------------|------------|--------
TOTALS     |                       | 17,650.00  |                       | 1,450.00   | NET: 16,200
`
    },
    { 
      type: 'PDF', 
      title: 'Inventory Checklist 2024', 
      color: 'bg-red-100 text-red-700',
      filename: 'Inventory_Checklist_2024.txt',
      content: `
STOCK AUDIT CHECKLIST
---------------------
[ ] ITEM NAME              | SKU      | PHYSICAL COUNT | SYSTEM COUNT | DISCREPANCY
[ ] _______________________|__________|________________|______________|____________
[ ] _______________________|__________|________________|______________|____________
[ ] _______________________|__________|________________|______________|____________

AUDIT PROCEDURES:
1. Cross-verify physical stock with billing system every 15 days.
2. Tag items with less than 1 month shelf-life for clearance sales.
3. Review storage temperature and packaging integrity for food items.
4. Update Re-order Points (ROP) based on previous month high-movers.
`
    },
    { 
      type: 'Excel', 
      title: 'Sales Performance Sheet', 
      color: 'bg-blue-100 text-blue-700',
      filename: 'Sales_Performance_Analysis.txt',
      content: `
PERFORMANCE ANALYTICS
---------------------
METRIC                     | WEEK 1 | WEEK 2 | WEEK 3 | WEEK 4 | TARGET
---------------------------|--------|--------|--------|--------|--------
TOTAL FOOTFALL             | 520    | 480    | 610    | 590    | 2,500
TOTAL BILLS GENERATED      | 145    | 130    | 190    | 185    | 800
CONVERSION %               | 27.8%  | 27.0%  | 31.1%  | 31.3%  | 32.0%
AVERAGE BILL VALUE (₹)     | 420    | 445    | 480    | 465    | 500
GROSS REVENUE (₹)          | 60,900 | 57,850 | 91,200 | 86,025 | 4,00,000
`
    }
  ];

  return (
    <div className="py-12 sm:py-20 animate-in fade-in duration-700 bg-white">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="text-center mb-16 sm:mb-20 space-y-4">
          <h1 className={`text-4xl sm:text-5xl font-black text-[#001A3D] ${isIndic ? 'leading-relaxed' : ''}`}>{t.navResources}</h1>
          <p className="text-gray-500 text-sm sm:text-xl max-w-2xl mx-auto font-medium">
            Professional business tools optimized for small retail growth in Gujarat.
          </p>
        </div>

        {/* Growth Calculator Section */}
        <section className="mb-24 sm:mb-32">
          <div className="bg-[#001A3D] rounded-[2.5rem] sm:rounded-[3rem] overflow-hidden shadow-2xl grid grid-cols-1 lg:grid-cols-2 border-4 border-primary/20">
            <div className="p-8 sm:p-12 lg:p-20 text-white space-y-6 sm:space-y-8">
              <div className="bg-primary/20 p-3 rounded-xl w-fit">
                <Calculator className="w-6 h-6 sm:w-8 sm:h-8 text-primary" />
              </div>
              <h2 className={`text-3xl sm:text-4xl font-black ${isIndic ? 'leading-[1.4]' : ''}`}>{t.calcTitle}</h2>
              
              <div className="space-y-8">
                <div className="space-y-3">
                  <label className="text-[10px] font-black uppercase tracking-widest text-gray-500">Shop Category</label>
                  <input 
                    type="text"
                    value={shopType}
                    onChange={(e) => setShopType(e.target.value)}
                    placeholder="e.g. Mobile, Stationery..."
                    className="w-full bg-white/5 border border-white/10 rounded-xl p-4 font-bold outline-none focus:ring-2 focus:ring-primary transition-all text-sm sm:text-base text-white placeholder:text-white/20"
                  />
                </div>
                <div className="space-y-3">
                  <label className="text-[10px] font-black uppercase tracking-widest text-gray-500">{t.calcMonthlySales}</label>
                  <input 
                    type="range" min="10000" max="1000000" step="5000" 
                    value={sales} onChange={(e) => setSales(Number(e.target.value))}
                    className="w-full accent-primary h-2 bg-gray-800 rounded-lg appearance-none cursor-pointer"
                  />
                  <p className="text-right font-black text-xl text-primary">₹{sales.toLocaleString()}</p>
                </div>
              </div>
            </div>
            <div className="bg-white p-8 sm:p-12 lg:p-20 flex flex-col justify-center text-center space-y-6 sm:space-y-8">
              <p className="text-gray-400 text-[10px] font-black uppercase tracking-widest">{t.calcResult}</p>
              <div className="flex flex-col items-center justify-center min-h-[140px] px-4 overflow-hidden">
                <p className="text-[clamp(2.5rem,14vw,5.5rem)] font-black text-primary leading-none tracking-tighter drop-shadow-sm whitespace-nowrap">
                  ₹{Number(potential).toLocaleString()}
                </p>
                <div className="mt-4 flex items-center space-x-2 bg-green-50 text-green-600 px-4 py-1.5 rounded-full border border-green-100">
                  <Sparkles size={14} className="animate-pulse" />
                  <span className="text-[10px] sm:text-sm font-black uppercase tracking-widest">+30% Growth Potential</span>
                </div>
              </div>
              <button 
                onClick={() => handleDownload('ShopSahay_Master_Growth_Pack.txt', 'Master Resource Pack: Individual templates provided below for detailed tracking.')}
                className="bg-[#001A3D] text-white py-5 rounded-2xl font-black text-xs sm:text-base uppercase tracking-widest transition-all shadow-xl hover:bg-[#001A3D] active:scale-95"
              >
                Download Master Resource Pack
              </button>
            </div>
          </div>
        </section>

        {/* Free Templates */}
        <div className="mb-24 sm:mb-32">
           <div className="flex items-center space-x-4 mb-10 sm:mb-12">
              <h2 className="text-2xl sm:text-3xl font-black text-[#001A3D] uppercase tracking-tighter">Business Templates</h2>
              <div className="flex-grow h-px bg-gray-100"></div>
           </div>
           <div className="grid grid-cols-1 md:grid-cols-3 gap-6 sm:gap-8">
              {freebies.map((item, i) => (
                <div key={i} className="group bg-gray-50 p-8 rounded-[2rem] border border-gray-100 hover:bg-white hover:shadow-2xl transition-all duration-500 relative flex flex-col justify-between h-72 overflow-hidden">
                   <div className="absolute top-0 right-0 w-32 h-32 bg-primary/5 rounded-full blur-2xl -mr-16 -mt-16"></div>
                   <div>
                     <span className={`${item.color} px-4 py-1.5 rounded-xl text-[10px] font-black uppercase tracking-widest inline-block mb-4 shadow-sm`}>{item.type}</span>
                     <h3 className="text-xl font-black text-[#001A3D] group-hover:text-primary transition-colors leading-tight">{item.title}</h3>
                   </div>
                   
                   <button 
                     onClick={() => handleDownload(item.filename, item.content)}
                     className="bg-primary text-white p-5 rounded-2xl shadow-lg flex items-center justify-between font-black uppercase tracking-widest text-[11px] transition-none hover:bg-primary"
                   >
                      <span className="flex items-center">Download File <Download className="ml-2 w-4 h-4" /></span>
                   </button>
                </div>
              ))}
           </div>
        </div>
      </div>
    </div>
  );
};

export default Resources;
